"""rename department

Revision ID: ac9967014e0e
Revises: 8734e9c5c955
Create Date: 2025-04-06 03:05:22.100628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac9967014e0e'
down_revision = '8734e9c5c955'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # we remove this when we are renaming the table
    # op.create_table('departments',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('name', sa.String(), nullable=False),
    # sa.Column('address', sa.String(), nullable=True),
    # sa.PrimaryKeyConstraint('id')
    # )
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # we remove this when we are renaming the table
    # op.create_table('department',
    # sa.Column('id', sa.INTEGER(), nullable=False),
    # sa.Column('name', sa.VARCHAR(), nullable=False),
    # sa.Column('address', sa.VARCHAR(), nullable=True),
    # sa.PrimaryKeyConstraint('id')
    # )
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
