"""rename address

Revision ID: d093b1bc9ef7
Revises: ac9967014e0e
Create Date: 2025-04-06 03:34:10.412755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd093b1bc9ef7'
down_revision = 'ac9967014e0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # remove/replace with when changing a column name
    # op.add_column('departments', sa.Column('location', sa.String(), nullable=True))
    # op.drop_column('departments', 'address')
    op.alter_column('departments', 'address', new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('departments', sa.Column('address', sa.VARCHAR(), nullable=True))
    # op.drop_column('departments', 'location')
    op.alter_column('departments', 'location', new_column_name='address')
    # ### end Alembic commands ###
